version: '3'

services:

  database:
    image: mysql:8.0
    container_name: seubarriga-mysql
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=finance
    ports: 
      - '3306:3306'
    networks:
      - database-network

  seubarriga-api:
    image: node:alpine
    container_name: seubarriga-api
    environment: 
      - DATABASE_URL=${DB_DIALECT}://${DB_USERNAME}:${DB_PASSWORD_ROOT}@database:${DB_PORT}/${DB_NAME}
    volumes:
      - .:/usr/app
    ports:
      - '3000:3000'
      # Prisma Studio
      - '5555:5555'
    build: 
      dockerfile: Dockerfile
    depends_on: 
      - database
    networks:
      - database-network
    command: sh -c "npm run dev" 

networks:
  database-network:
    driver: bridge
