version: '3'

services:

  mariadb:
    image: mariadb
    environment:
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD_ROOT}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - .docker/dbdata:/var/lib/mysql

  finance-api:
    image: node:alpine
    container_name: finance_api
    volumes:
      - ./.:/home/app
    build: 
      dockerfile: Dockerfile
      context: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    depends_on: 
      - mariadb
    command: sh -c "npm start"
