version: '3'

services:

  database:
    image: mysql:8.0
    container_name: finance-mysql
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=finance
    ports: 
      - '3306:3306'
    networks:
      - database-network

  finance-api:
    image: node:alpine
    container_name: finance-api
    volumes:
      - .:/usr/app
    build: 
      dockerfile: Dockerfile
      context: .
    environment:
      - NODE_ENV=development
    depends_on: 
      - database
    networks:
      - database-network
    command: sh -c "npm run dev" 
  
networks:
  database-network:
    driver: bridge
