version: '3'

services:

  mariadb:
    image: mariadb
    container_name: finance-mariadb
    environment:
      - MARIADB_DATABASE=${DB_DATABASE}
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD_ROOT}
      - MARIADB_USER=${DB_USERNAME}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    volumes:
      - .docker/dbdata:/var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - database-network

  finance-api:
    image: node:alpine
    container_name: finance-api
    volumes:
      - .:/usr/app
    build: 
      dockerfile: Dockerfile
      context: .
    environment:
      - NODE_ENV=development
    depends_on: 
      - mariadb
    networks:
      - database-network
    command: sh -c "npm run dev" 
  
networks:
  database-network:
    driver: bridge
